version: "3.7"
services:
  cache:
    container_name: ${CACHE_CONTAINER_NAME}
    image: redis:6
    networks:
      - directus

  database:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:5.7.8
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - directus
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  directus:
    container_name: ${DIRECTUS_CONTAINER_NAME}
    command: >
      sh -c "
        mkdir ./schema
        npx directus bootstrap && npx directus start
      "
    image: directus/directus:${DIRECTUS_VERSION}
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
      - ./schema:/directus/schema
    networks:
      - directus
    depends_on:
      - cache
      - database
    ports:
      - "80:80"
      - "443:443"
      - "8055:8055"
    environment:
      KEY: "${DIRECTUS_KEY}"
      SECRET: "${DIRECTUS_SECRET}"
      ACCESS_TOKEN_TTL: "${DIRECTUS_TOKEN_TTL}"
      DB_CLIENT: "mysql"
      DB_HOST: database
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      CACHE_ENABLED: "${DIRECTUS_CACHE_ENABLED}"
      CACHE_STORE: "${DIRECTUS_CACHE_DRIVER}"
      CACHE_REDIS: "${DIRECTUS_CACHE_HOST}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      CACHE_AUTO_PURGE: "true"
      CORS_ENABLED: "${DIRECTUS_CORS_ENABLED}"
      CORS_ORIGIN: "${DIRECTUS_CORS_ORIGIN}"
      CORS_METHODS: "${DIRECTUS_CORS_METHODS}"

volumes:
  db_data:

networks:
  directus:
    name: directus
